name: CI - Todo API

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # importante para o SonarCloud ter histórico de commits

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ler metadados do app
        id: meta
        run: |
          APP_NAME=$(sed -n 's/^__app_name__ = "\(.*\)"/\1/p' app/version.py)
          VERSION=$(sed -n 's/^__version__ = "\(.*\)"/\1/p' app/version.py)
          BUILD=$(sed -n 's/^__build__ = "\(.*\)"/\1/p' app/version.py)

          echo "app_name=$APP_NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "build=$BUILD" >> $GITHUB_OUTPUT

      - name: Exibir versão
        run: |
          echo "Versão detectada: ${{ steps.meta.outputs.app_name }}"
          echo "Versão detectada: ${{ steps.meta.outputs.version }}"
          echo "Versão detectada: ${{ steps.meta.outputs.build }}"

      - name: Usar no Docker
        run: |
          docker build \
            --build-arg VERSION=${{ steps.meta.outputs.version }} \
            --build-arg APP_NAME=${{ steps.meta.outputs.app_name }} \
            .
          
      - name: Atualizar __build__ com SHA
        run: |
          sed -i "s/^__build__.*/__build__ = \"${GITHUB_SHA}\"/" app/version.py

      - name: Rodar testes com coverage (pytest-cov)
        env:
          PYTHONPATH: .
        run: |
          pytest -v --cov=app --cov-report=term-missing --cov-report=xml

      # Opcional: upload do coverage.xml como artifact (debug)
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}  # necessário para PR decoration
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=claudio-bianco_pipeline-ci-cd-python
            -Dsonar.organization=claudiobianco
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.projectName=crud-python-todo-api
            -Dsonar.sources=app
            -Dsonar.tests=tests
            -Dsonar.sourceEncoding=UTF-8
